name: Trigger Shell Script on YAML Update

on:
  push:
    branches:
      - prod
    paths:
      - 'k8s/prod/*.yaml'
jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug - List Changed Files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD

      - name: Check for YAML changes
        id: yaml-check
        run: |
          echo "Checking for YAML changes..."
          if git diff --name-only HEAD^ HEAD | grep -qE 'k8s/(prod|stg)/.*\.yaml'; then
            echo "YAML files changed"
            echo "changes=true"
          else
            echo "No YAML changes"
            echo "changes=false"
          fi

      - name: Debug - Show Change Status
        run: |
          echo "YAML changes check complete"
          echo "Change status: ${{ steps.yaml-check.outputs.changes }}"

      - name: Run Shell Script
        if: steps.yaml-check.outputs.changes == 'true'
        run: |
          echo "Running shell script..."
          chmod +x ./k8s/run-script.sh
          ./k8s/run-script.sh
