name: K8s Image Update Workflow

on:
  push:
    branches:
      - prod
    paths:
      - 'k8s/prod/**/*.yaml'
      - 'k8s/stg/**/*.yaml'

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep 'k8s/\(prod\|stg\)/.*\.yaml$' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Check if yaml files changed
        id: check-yaml
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.files }}"
          if [ ! -z "$CHANGED_FILES" ]; then
            echo "yaml_changed=true" >> $GITHUB_OUTPUT
          else
            echo "yaml_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Make script executable
        if: steps.check-yaml.outputs.yaml_changed == 'true'
        run: |
          chmod +x ./trigger.sh  # Shell script adını buraya yazın

      - name: Run update script
        if: steps.check-yaml.outputs.yaml_changed == 'true'
        run: |
          ./trigger.sh  # Shell script adını buraya yazın
