name: Image Update Detection

on:
  push:
    branches:
      - main 
      - prod # main branch'te çalışacak şekilde değiştirildi
    paths:
      - '**/*.yaml'
      - '**/*.yaml'

jobs:
  detect-image-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for image changes
        id: check-changes
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E 'k8s/(prod|stg)/.+\.yaml$' || true)
          
          IMAGE_CHANGED=false
          for file in $CHANGED_FILES; do
            if git diff HEAD^ HEAD "$file" | grep -q '^[+-].*image:'; then
              IMAGE_CHANGED=true
              echo "Image change detected in $file"
              echo "changed_file=$file" >> $GITHUB_OUTPUT
            fi
          done
          
          echo "has_image_changes=$IMAGE_CHANGED" >> $GITHUB_OUTPUT
          
          # Debug bilgisi
          echo "Debug Information:"
          echo "Changed files: $CHANGED_FILES"
          echo "Image changed: $IMAGE_CHANGED"

      - name: Run trigger script
        if: steps.check-changes.outputs.has_image_changes == 'true'
        run: |
          echo "Running trigger.sh script..."
          chmod +x ./trigger.sh
          ./trigger.sh
