name: Detect Image Changes

on:
  push:
    branches:
      - prod
      - stg
      - main

jobs:
  detect-image-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Git
        run: git fetch --all

      - name: Detect image changes in YAML files
        run: |
          echo "Starting image change detection..."

          # Get current branch
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch: $CURRENT_BRANCH"

          # Find changed files in k8s/prod or k8s/stg directories
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E 'k8s/(prod|stg)/.+\.yaml$' || true)
          echo "Changed YAML files:"
          echo "$CHANGED_FILES"

          IMAGE_CHANGED=false

          for file in $CHANGED_FILES; do
            echo "Checking file: $file"
            # Check if there is an image line change
            if git diff HEAD^ HEAD "$file" | grep -E '^\+.*image:'; then
              echo "Image change detected in $file"
              IMAGE_CHANGED=true
            fi
          done

          if [ "$IMAGE_CHANGED" = true ]; then
            echo "Triggering the shell script due to image change."
            ./your-shell-script.sh
          else
            echo "No image changes detected."
          fi
