name: Run Script on Every Commit

on:
  push:
    branches:
      - main
      - prod
    paths:
      - '**/*.yaml'

jobs:
  run-script-on-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run trigger script
        run: |
          echo "Running trigger.sh due to commit..."
          chmod +x ./trigger.sh
          ./trigger.sh
