name: Image Update Detection

on:
  push:
    branches:
      - prod
    paths:
      - 'k8s/prod/**/*.yaml'
      - 'k8s/stg/**/*.yaml'

jobs:
  detect-image-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Son 2 commit'i al (değişiklikleri karşılaştırmak için)

      - name: Check for image changes
        id: check-changes
        run: |
          # Son commit'teki değişiklikleri al
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep -E 'k8s/(prod|stg)/.+\.yaml$' || true)
          
          # Her değişen dosyada image değişikliği var mı kontrol et
          IMAGE_CHANGED=false
          for file in $CHANGED_FILES; do
            if git diff HEAD^ HEAD "$file" | grep -q '^[+-].*image:'; then
              IMAGE_CHANGED=true
              echo "Image change detected in $file"
              echo "changed_file=$file" >> $GITHUB_OUTPUT
            fi
          done
          
          echo "has_image_changes=$IMAGE_CHANGED" >> $GITHUB_OUTPUT

      - name: Run shell script if image changed
        if: steps.check-changes.outputs.has_image_changes == 'true'
        run: |
          # Shell script'e execute yetkisi ver
          chmod +x ./trigger.sh
          
          # Script'i çalıştır
          ./trigger.sh
