name: Detect Image Changes

on:
  push:
    branches:
      - prod
      - main  # Add other branches if needed

jobs:
  detect-image-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git fetch --prune --unshallow
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Check for image changes
        run: |
          echo "Starting image change detection..."
          echo "Current branch: $(git branch --show-current)"
          
          # Get the changed YAML files
          changed_files=$(git diff HEAD^ HEAD --name-only -- *.yaml prod/*.yaml)
          
          if [ -z "$changed_files" ]; then
            echo "No YAML files changed."
          else
            echo "Changed YAML files:"
            echo "$changed_files"
            
            # Check for image changes in the changed YAML files
            for file in $changed_files; do
              echo "Checking $file for image changes..."
              if git diff HEAD^ HEAD -- "$file" | grep -q 'image:'; then
                echo "Image change detected in $file."
                # Call your shell script here
                ./your-shell-script.sh
              else
                echo "No image changes detected in $file."
              fi
            done
          fi
